baseurl: https://lydia7635.github.io
languageCode: zh-tw
theme: hugo-theme-stack
paginate: 10
title: Tech Gift Box

# Change it to your Disqus shortname before using
disqusShortname: lydia7635

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
defaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

# enable inline shortcodes
enableInlineShortcodes: true

# Enable Emoji emoticons support for page content
enableEmoji: true

# Enable .GitInfo object for each page (if the Hugo site is versioned by Git).
# This will then update the Lastmod parameter for each page using the last git commit date for that content file.
enableGitInfo: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.ico

    footer:
        since: 2021
        customText:

    dateFormat:
        published: 2006/01/02
        lastUpdated: 2006/01/02

    sidebar:
        emoji: 💻
        subtitle: Hello! Welcome to Tech Gift Box :)
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        readingTime: false
        license:
            enabled: true
            default: Licensed under CC BY-NC

    comments:
        enabled: true
        provider: disqus

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: lydia7635

            # Available values: summary, summary_large_image
            card: summary

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: 

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              icon: home

        - identifier: about
          name: About
          url: about
          weight: -90
          params:
              icon: user

        - identifier: categories
          name: Categories
          url: categories
          weight: -80
          params:
              icon: categories

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          params:
              icon: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          params:
              icon: search

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/lydia7635
          params:
              icon: brand-github

        - identifier: linkedin
          name: LinkedIn
          url: https://www.linkedin.com/in/lydia7635/
          params:
              icon: brand-linkedin

related:
    includeNewer: true
    threshold: 75
    toLower: false
    indices:
        - name: tags
          weight: 50

        - name: categories
          weight: 30

markup:
    highlight:
        guessSyntax: false
        lineNos: true
        lineNumbersInTable: true    # Give copy-and-paste friendly code blocks
        tabWidth: 4
        style: dracula
        noClasses: true             # Use inline styles instead of CSS classes
    goldmark:
        renderer:
            unsafe: true
